let parem ={
    "lang": languageKey,
    "regionalDTConsent": true,
    "lastName": infoValue.lastName,
    "marketingConsent": true,
    // "birthDay": infoValue.birthDay,
    "title": areaCode.key,
    "firstName": infoValue.firstName,
    "tncConsent": true,
    "email": emailValue.value,
    "country":countriesVale.key,
    "city": region.key,
    "area": district.value,
    "ageRange": ageVale.key,
    "placeOfResidence": infoValue.placeOfResidence,
    "phoneCountry": iphoneCodeVale,
    // "birthMonth": infoValue.birthMonth,
    "gender": genderVale.key,
    "maritalStatus": marital.key,
    'workEmail':workEmailValue.value,
    "occupation": occupationValue.key,
    "facebookId": infoValue.facebookId,
    "phoneNumber": phoneNumber,
    'creditCardRegisteredName':cardRegisteredName.value
}
